[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [
    { access = "read-write", path = "../circuit/target" },
    { access = "read-write", path = "/tmp/" },
]
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
"local" = "http://localhost:8545"
"base_sepolia" = "${BASE_SEPOLIA_RPC_URL}"
"sepolia" = "${SEPOLIA_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
