export const styles = {
  container: {
    fontFamily: "'Inter', -apple-system, sans-serif",
    maxWidth: "1200px",
    margin: "0 auto",
    padding: "20px",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "15px 20px",
    backgroundColor: "#ffffff",
    borderRadius: "10px",
    boxShadow: "0 2px 8px rgba(0, 0, 0, 0.08)",
    marginBottom: "20px",
  },
  title: {
    fontSize: "22px",
    fontWeight: 700,
    color: "#1a1a1a",
    margin: 0,
  },
  walletInfo: {
    display: "flex",
    alignItems: "center",
    gap: "15px",
  },
  networkBadge: {
    display: "flex",
    alignItems: "center",
    backgroundColor: "#f1f5f9",
    padding: "6px 12px",
    borderRadius: "20px",
    fontSize: "14px",
  },
  networkIndicator: {
    width: "8px",
    height: "8px",
    borderRadius: "50%",
    backgroundColor: "#10b981",
    marginRight: "8px",
  },
  accountBadge: {
    backgroundColor: "#f1f5f9",
    padding: "6px 12px",
    borderRadius: "20px",
    fontSize: "14px",
    fontFamily: "monospace",
  },
  connectButton: {
    backgroundColor: "#3b82f6",
    color: "white",
    border: "none",
    padding: "8px 16px",
    borderRadius: "6px",
    cursor: "pointer",
    fontWeight: 600,
  },
  mainContent: {
    display: "flex",
    gap: "20px",
  },
  leftPanel: {
    flex: 1,
    backgroundColor: "#ffffff",
    borderRadius: "10px",
    padding: "20px",
    boxShadow: "0 2px 8px rgba(0, 0, 0, 0.08)",
  },
  rightPanel: {
    flex: 1,
    backgroundColor: "#ffffff",
    borderRadius: "10px",
    padding: "20px",
    boxShadow: "0 2px 8px rgba(0, 0, 0, 0.08)",
  },
  panelTitle: {
    fontSize: "18px",
    fontWeight: 600,
    marginBottom: "20px",
    color: "#333",
  },
  challengeList: {
    listStyle: "none",
    padding: 0,
    margin: 0,
  },
  challengeItem: {
    display: "flex",
    alignItems: "center",
    padding: "12px",
    borderBottom: "1px solid #eee",
    cursor: "pointer",
  },
  challengeSelected: {
    backgroundColor: "#f0f9ff",
    borderRadius: "6px",
  },
  challengeInfo: {
    marginLeft: "12px",
  },
  challengeName: {
    fontWeight: 600,
    marginBottom: "4px",
  },
  challengeDescription: {
    fontSize: "14px",
    color: "#666",
  },
  buttonLarge: {
    backgroundColor: "#3b82f6",
    color: "white",
    border: "none",
    padding: "12px 20px",
    borderRadius: "6px",
    cursor: "pointer",
    fontWeight: 600,
    width: "100%",
    marginTop: "20px",
  },
  buttonDisabled: {
    opacity: 0.6,
    cursor: "not-allowed",
  },
  proofContainer: {
    marginTop: "20px",
    padding: "15px",
    backgroundColor: "#f8fafc",
    borderRadius: "6px",
    border: "1px solid #e2e8f0",
    maxHeight: "150px",
    overflowY: "auto" as const,
  },
  proofText: {
    fontFamily: "monospace",
    fontSize: "12px",
    wordBreak: "break-all" as const,
  },
  loading: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
  },
  txSuccess: {
    color: "#059669",
    fontWeight: 600,
    display: "flex",
    alignItems: "center",
    gap: "6px",
  },
};
